services:
  
  backend:
    build: ./Backend
    ports: 
      - 7000:7000
    volumes:
      - ./Backend:/app
      - backend-node-modules:/app/node_modules

    command: npx nodemon -L server.js


volumes:
    backend-node-modules: